name: Build and Deploy Wheel Action
description: Build and deploy the wheel file to the Synapse workspace(s) and spark pool. Includes removing the current version.
inputs:
  CREDS:
    required: true 
    description: Azure Credentials coming from the original workflow
  TARGET_WS: 
    description: Target Synapse name to deploy the wheel to 
    required: true 
  SPARK_POOL_NAME:
    description: Synapse Spark Pool to deploy the wheel to
    required: true
  WHEEL_FILE_NAME:
    description: Wheel file name to build/deploy to Synapse 
    required: false

runs:
  using: composite 
  steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.CREDS }}
        enable-AzPSSession: true 

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Build Python Wheel 
      run: |
        python -m pip install wheel 
        python setup.py bdist_wheel
      shell: pwsh 

    - name: Run Python Script from Powershell 
      uses: azure/powershell@v1 
      with:
        azPSVersion: latest 
        inlineScript: |
          Import-Module Az.Synapse
          python ${{ github.action_path }}/SynapseBuildWheelScript.py


    # - name: Run Python Script
    #   run: python ${{ github.action_path }}/SynapseBuildWheelScript.py
    #   shell: pwsh