name: Build and Deploy Wheel Action
description: Build and deploy the wheel file to the Synapse workspace(s) and Spark Pool. Includes removing the current version.
inputs:
  CREDS:
    required: true 
    description: Azure Credentials coming from the original workflow
  TARGET_WS: 
    description: Target Synapse name to deploy the wheel to 
    required: true 
  SPARK_POOL_NAME:
    description: Synapse Spark Pool to deploy the wheel to
    required: true
  WHEEL_FILE_NAME:
    description: Wheel file name to build/deploy to Synapse 
    required: true

outputs:
  ErrorOutput:
    description: If Python script below fails, ErrorOutput would be saved as 'FAILED'.
    value: ${{ steps.run-python-script.outputs.ErrorOutput }} 

runs:
  using: composite 
  steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.CREDS }}
        enable-AzPSSession: true 

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Build Python Wheel 
      run: |
        pip install build
        python -m build
      shell: pwsh 

    - name: Run Python Script from Powershell
      id: run-python-script
      env:
        TARGET_WS: ${{ inputs.TARGET_WS }}
        SPARK_POOL_NAME: ${{ inputs.SPARK_POOL_NAME }}
        WHEEL_FILE_NAME: ${{ inputs.WHEEL_FILE_NAME }}
      uses: azure/powershell@v1 
      with:
        azPSVersion: latest 
        inlineScript: |
          Import-Module Az.Synapse
          python ${{ github.action_path }}/SynapseBuildWheelScript.py
    
    - name: Check if the Python Script Failed
      if: ${{ steps.run-python-script.outputs.ErrorOutput == 'FAILED' }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Run Python Script from Powershell step failed. See above in this screen for the error message')