name: Synapse Build and Deploy Wheel to Workspace Packages and Spark Pool.

on:
  workflow_dispatch:
    inputs:
      deploy-to-synapse-ws-1:
        required: true 
        type: boolean
        default: true 
        description: Deploy wheel to Synapse workspace 1. 
      deploy-to-synapse-ws-2:
        required: true 
        type: boolean 
        default: false 
        description: Deploy wheel to Synapse Workspace 2. 
        # can add other Synapse workspaces here

jobs:
  deploy-to-synapse-ws-1:
    if: ${{ github.event.inputs.deploy-to-synapse-ws-1 == 'true' }}
    runs-on: windows-latest
    environment: env1 # or whatever env name in GitHub Secrets
    steps:  
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Synapse Build Deploy Wheel
        uses: ./.github/actions/synapse_build_deploy_wheel_action
        with:
          CREDS: ${{ secrets.AZURE_CREDENTIALS }}
          TARGET_WS: ${{ secrets.TARGET_WS }}
          SPARK_POOL_NAME: ${{ secrets.SPARK_POOL_NAME }}
          WHEEL_FILE_NAME: ${{ secrets.WHEEL_FILE_NAME2 }}

  deploy-to-synapse-ws-2:
    if: ${{ github.event.inputs.deploy-to-synapse-ws-2 == 'true' }}
    runs-on: windows-latest
    environment: env2 # or whatever env name in GitHub Secrets
    steps:  
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Synapse Build Deploy Wheel
        uses: ./.github/actions/synapse_build_deploy_wheel_action
        with:
          CREDS: ${{ secrets.AZURE_CREDENTIALS }}
          TARGET_WS: ${{ secrets.TARGET_WS }}
          SPARK_POOL_NAME: ${{ secrets.SPARK_POOL_NAME }}
          WHEEL_FILE_NAME: ${{ secrets.WHEEL_FILE_NAME }}
  
  # Add more workspaces 